version: '3.8'

services:
 # --- API Gateway ---
  nginx:
    image: nginx:1.21
    ports:
      - "8080:80" # This is now the ONLY port we should access from the outside
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount our config file
    depends_on:
      - user_service
      - bookmark_service

  auth_validator:
    build: ./auth_validator
    environment:
      # Define the shared secret key here
      - DJANGO_SECRET_KEY=my-super-secret-and-long-key-that-is-not-this

  # User Service Definition
  user_service:
    build:
      context: ./user_service  # Path to the Dockerfile
    
    volumes:
      - ./user_service:/app # Mount local code for live reloading
    command: python manage.py runserver 0.0.0.0:8000 # Override CMD for dev
    environment:
      - DB_NAME=user_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db_user # This is the service name of our database container
      - DJANGO_SECRET_KEY=my-super-secret-and-long-key-that-is-not-this
    depends_on:
      - db_user # Wait for the DB to be ready

  # User Service Database
  db_user:
    image: postgres:16
    ports:
         - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
# --- Bookmark Service ---
  bookmark_service:
    build:
      context: ./bookmark_service # Path to the new service
    
    volumes:
      - ./bookmark_service:/app
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      - DB_NAME=bookmark_db
      - DB_USER=bookmark_user
      - DB_PASSWORD=password
      - DB_HOST=db_bookmark # Connects to its OWN database service
    depends_on:
      - db_bookmark

  db_bookmark:
    image: postgres:16
    ports:
         - "5433:5432"
    volumes:
      - bookmark_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bookmark_db
      - POSTGRES_USER=bookmark_user
      - POSTGRES_PASSWORD=password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://nginx:80
    depends_on:
      - nginx

volumes:
  user_postgres_data:
  bookmark_postgres_data: # Define the new volume

